import React, { FunctionComponent } from "react";
import { Box, Flex, Text, Heading, Image } from "@chakra-ui/core";
import inventory from "../../assets/images/inventory.png";
import financial_control from "../../assets/images/financial_control.png";

const aboutDescription =
  "PayPhone is a multi-fiat-currency e-wallet which aims to give user full control of their funds using a public-private key infrastructure. A secure portal facilitates end to end - B2C / B2B encrypted Smart Contracts powered by Blockchain to help the user against fraud when making purchases in the unorganized market. ";
const visionDescription =
  "We work towards the goal of eliminating paper waste generated by physical receipts with the help of item wise inventory management powered through e - receipts.With the help of an AI powered database, PayPhone aims to change the way people manage their finances. ";

export const Features: FunctionComponent = () => (
  <Flex
    id="features"
    px={[10, 20, 30, 40]}
    py={[10, 10, 20, 20]}
    color="black"
    align="center"
    textAlign="left"
    direction="column"
    backgroundColor="primary"
  >
    <Box width="80vw">
      <Heading textAlign="center" as="h1" size="2xl">
        Your multi-currency wallet
      </Heading>
      <Flex direction="row" justify="space-between">
        <Flex direction="column" align="center">
          <Image src={inventory}></Image>
          <Heading as="h3" size="md">
            Track your expenses
          </Heading>
        </Flex>
        <Image src={financial_control}></Image>
      </Flex>
    </Box>
    <Box width="60vw">
      <Heading textAlign="center" as="h1" size="lg" p={5}>
        Our Vision
      </Heading>
      <Text fontSize={["md", "md", "lg", "lg"]}>{visionDescription}</Text>
    </Box>
  </Flex>
);
